language: objective-c
osx_image: xcode7

install:
- npm install -g playground

script:
# Generate README.playground from README.md
- make
- git config --global push.default simple
- git diff-files --exit-code; if [[ "$?" == "1" ]]; then git commit -a -m "Playground update from Travis [ci skip]"; git push; fi
- pushd IDZSwiftCommonCrypto
- rm -rf CommonCrypto
- ./GenerateCommonCryptoModule iphonesimulator9.0 .
- cat CommonCrypto/module.map
- pwd
- xcodebuild build -scheme IDZSwiftCommonCrypto -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0'
# Remove testing pending solution to https://github.com/travis-ci/travis-ci/issues/2829
- xcodebuild test -scheme IDZSwiftCommonCrypto -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0'
- popd
